### ISSUE TITLE
Upgrade enterprise-subsidy to Django 4.2

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/enterprise-subsidy#152]
Kindly copy this tasklist to the PR as well.

```[tasklist]
### Tasks
- [ ] Add `USE_DEPRECATED_PYTZ` to the settings, also add `pytz` to `base.in` if not there already. (more info: https://docs.djangoproject.com/en/4.2/releases/4.0/#zoneinfo-default-timezone-implementation) (see content below)
- [ ] Override common constraint of Django
- [ ] Run make upgrade with Django 4.2
- [ ] Drop testing of Django 3.2
- [ ] Inform the owning team about the change in the hashing algorithm (More info: https://github.com/edx/edx-arch-experiments/issues/453)
- [ ] Check if `CSRF_TRUSTED_ORIGINS` is defined in ArgoCD configs, if yes, update those to use the scheme. (more info: https://github.com/edx/edx-arch-experiments/issues/459)
```

### USE_DEPRECATED_PYTZ

```
# Django 4.0+ uses zoneinfo if this is not set. We can remove this and
# migrate to zoneinfo after Django 4.2 upgrade. See more on following url
# https://docs.djangoproject.com/en/4.2/releases/4.0/#zoneinfo-default-timezone-implementation
USE_DEPRECATED_PYTZ = True
```

**Comment by iamsobanjaved** [comment]
Related internal PR: 
- https://github.com/edx/edx-internal/pull/9350
